version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.bash
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
