spring:
  security:
    oauth2:
      client:
        registration:
          apple:
            redirect-uri: ${client.base-url}/sign-in/apple/callback
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - openid
          kakao:
            redirect-uri: ${client.base-url}/sign-in/kakao/callback
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
          naver:
            redirect-uri: ${client.base-url}/sign-in/naver/callback
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
          dev:
            provider: kakao
            redirect-uri: ${client.dev-url}/sign-in/dev/callback
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            issuer-uri: https://appleid.apple.com
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response/id

  profiles:
    include: secret
    active: prod
  servlet:
    multipart:
      max-file-size: 10MB # 파일 최대 사이즈 + 서비스단 별도 제한 10MB
      max-request-size: 10MB # 요청 당 최대 사이즈 + 서비스단 별도 제한 10MB

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"
