spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true # sql 보기 편하게 출력
    use_sql_comments: true
    datasource:
      url: jdbc:h2:mem:ootdzip
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        timeout: 10
    profiles:
      include: secret
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10

client:
  base-url: https://dev.ootdzip.com
  dev-url: http://localhost:3000


logging: #로그 레벨을 정하는 것
  level:
    org.hibernate.SQL: debug #JPA 하이버네이트가 생성하는 SQL 로그
    org.hibernate.orm.jdbc.bind: debug # 스프링 3.0 이후 변경됨
    zip.ootd.ootdzip.oauth.OAuth2AuthenticationFailureHandler: debug # 로그인 실패 시 로그

# Token config
authorization:
  issuer: https://dev.ootdzip.com
  audience: https://dev-ootdzip.com
  access-token-time-to-live: 5184000  # 30 minutes
  refresh-token-time-to-live: 5184000  # 60 days
