spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ootdzip
    username: ootdzip
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10
security:
  jwt:
    secret-key: fg+KVO+mAOI82PpNTvTr+qOGfDbnOWNzgI9vHfRT3cQ=
    signature-algorithm: HS256
    expires-in: 10800000
    refresh-token-expires-in: 604800000