spring:
  security:
    jwt:
      secret-key: # input jwt secret key
      signature-algorithm: # input jwt security algorithm
      expires-in: # input access token expires time
      refresh-token-expires-in: # input refresh token expires time
    oauth2:
      client:
        registration:
          google:
            client-id: # input google client id
            client-secret: # input google secret key
            scope: # input google information scope
            redirect_uri: # input google auth redirect uri
          kakao:
            app-rest-api-key: # input kakao secret key

cloud:
  aws:
    credentials:
      access-key: # input aws access key
      secret-key: # input asw secret key
    s3:
      bucket: # input your bucket name
    region:
      static: # input your bucket region
    stack:
      auto: false



