spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # input google client id
            client-secret: # input google secret key
            scope: # input google information scope
            redirect_uri: # input google auth redirect uri
          kakao:
            client-id: # kakao rest api app key
            client-secret: # kakao client secret

cloud:
  aws:
    credentials:
      access-key: # input aws access key
      secret-key: # input asw secret key
    s3:
      bucket: # input your bucket name
    region:
      static: # input your bucket region
    stack:
      auto: false

authorization:
  secret-key: # Jwt secret key
