spring:
  security:
    jwt:
      secret-key: # input jwt secret key
      signature-algorithm: # input jwt security algorithm
      expires-in: # input access token expires time
      refresh-token-expires-in: # input refresh token expires time
    oauth2:
      client:
        registration:
          google:
            client-id: # input google client id
            client-secret: # input google secret key
            scope: # input google information scope
            redirect_uri: # input google auth redirect uri
          kakao:
            app-rest-api-key: # input kakao secret key


