server:
  port: 8081

client:
  base-url: ootdzip.com

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false # 로그로 sql 구문을 출력하므로 사용안함
        format_sql: true # sql 보기 편하게 출력
        jdbc:
          batch_size: 100 # update문 하이버네이트 배치를 사용하기 위해 추가, (Insert는 적용불가, id 생성방식이 Identity 이기 때문)
        order_updates: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ootdzip # mariaDB 쿼리로그가 보고싶을시 ?&profileSQL=true&maxQuerySizeToLog=0
    username: ootdzip
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            redirect_uri: ${client.base-url}/login/callback/google
            scope:
              - email
              - profile
          kakao:
            redirect-uri: ${client.base-url}/login/callback/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id

  profiles:
    include: secret
  servlet:
    multipart:
      max-file-size: 100MB # 파일 최대 사이즈 + 서비스단 별도 제한 10MB
      max-request-size: 500MB # 요청 당 최대 사이즈 + 서비스단 별도 제한 50MB

logging: #로그 레벨을 정하는 것
  level:
    org.hibernate.SQL: debug #JPA 하이버네이트가 생성하는 SQL 로그
    org.hibernate.orm.jdbc.bind: trace # 스프링 3.0 이후 변경됨

# for swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    urls-primary-name: TEST API
    persist-authorization: true
    query-config-enabled: true
  pre-loading-enabled: true

# Token config
authorization:
  issuer: ootdzip
  audience: ootdzip
  access-token-time-to-live: 1800  # 30 minutes
  refresh-token-time-to-live: 5184000  # 60 days
